### ISSUE TITLE
와

### ISSUE THREAD

**Issue by HyungJu** [kykdev/naraewiz#1]
와 윈도우 bash로 하면 안느리신감... 
그래도 윈도우쪽이랑 파일 연동이되니까 편하긴 한것 같아요

**Comment by kykdev** [comment]
속도 면에선 우분투에서 직접 하는것과 다를 게 없더라구요. 사실 제 컴퓨터가 메인보드 문제인지 윈도우-우분투 듀얼 부팅 중인데 한 os로 부팅하면 다른 쪽이 먹통이 돼버려서 우분투를 쓰기가 좀.. 그렇다고 가상머신으로 돌리긴 싫고.. 결국 울며 겨자먹기로 윈도우 bash 씁니다.
